"""Compute weighted and stitched-path regime-mix strategy metrics."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from export_regime_metrics_csv import (
    annualized_return_from_returns,
    annualized_vol_from_returns,
    build_realized_vol_benchmark_regime,
    cvar_from_returns,
    max_drawdown_from_returns,
    sharpe_ratio_from_returns,
    strategy_return_series,
)


REGIME_ORDER = ["Low", "Mid", "High"]
WEIGHTED_METRIC_COLUMNS = [
    "Sharpe",
    "AnnualizedVol",
    "AnnualizedReturn",
    "MaxDrawdown",
    "CVaR",
]


PRESET_MIXES: dict[str, dict[str, str]] = {
    "hybrid_hysteresis_hybrid_trend_regime_switch": {
        "Low": "hybrid_ewma_regime__hysteresis_controller",
        "Mid": "hybrid_ewma_regime__trend_filter",
        "High": "regime_gjrgarch__regime_switch_controller",
    },
    "rshar_trend_rshar_trend_regime_trend": {
        "Low": "rshar_rates__trend_filter",
        "Mid": "rshar_rates__trend_filter",
        "High": "regime_gjrgarch__trend_filter",
    },
    "rshar_trend_dynamic_trend_dynamic_trend": {
        "Low": "rshar_rates__trend_filter",
        "Mid": "dynamic_precision_ensemble__trend_filter",
        "High": "dynamic_precision_ensemble__trend_filter",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compute weighted and stitched-path regime-mix strategy metrics using "
            "the CSV exported by scripts/export_regime_metrics_csv.py."
        )
    )
    parser.add_argument(
        "--input",
        default="results/estimator_controller_metrics_by_regime.csv",
        help="Input CSV generated by scripts/export_regime_metrics_csv.py.",
    )
    parser.add_argument(
        "--output",
        default="results/regime_mix_metrics.csv",
        help="Output CSV path for the regime-mix summary.",
    )
    parser.add_argument(
        "--path-output",
        default="results/regime_mix_daily_paths.csv",
        help="Output CSV path for the stitched daily return paths.",
    )
    parser.add_argument(
        "--results-dir",
        default="results",
        help="Directory containing strategy result parquet files.",
    )
    parser.add_argument(
        "--ann-factor",
        type=float,
        default=252.0,
        help="Annualization factor for return and volatility metrics.",
    )
    parser.add_argument(
        "--min-coverage-ratio",
        type=float,
        default=0.95,
        help="Coverage threshold passed to the benchmark regime builder.",
    )
    return parser.parse_args()


def weighted_mean(values: pd.Series, weights: pd.Series) -> float:
    vals = pd.to_numeric(values, errors="coerce")
    w = pd.to_numeric(weights, errors="coerce")
    mask = vals.notna() & w.notna()
    if not mask.any():
        return float("nan")
    total_weight = float(w.loc[mask].sum())
    if total_weight <= 0:
        return float("nan")
    return float(np.average(vals.loc[mask], weights=w.loc[mask]))


def load_input(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {"strategy", "regime", "n_obs", *WEIGHTED_METRIC_COLUMNS}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Missing required columns in {path}: {missing}")

    out = df.copy()
    out["regime"] = pd.Categorical(out["regime"], categories=REGIME_ORDER, ordered=True)
    return out.sort_values(["strategy", "regime"]).reset_index(drop=True)


def rows_for_mix(df: pd.DataFrame, mix_name: str, regime_map: dict[str, str]) -> pd.DataFrame:
    rows: list[pd.Series] = []
    for regime in REGIME_ORDER:
        strategy = regime_map[regime]
        match = df.loc[(df["strategy"] == strategy) & (df["regime"] == regime)].copy()
        if match.empty:
            raise ValueError(
                f"Missing row for mix '{mix_name}': strategy='{strategy}', regime='{regime}'."
            )
        rows.append(match.iloc[0])
    return pd.DataFrame(rows).reset_index(drop=True)


def summarize_weighted_mix(mix_name: str, rows: pd.DataFrame) -> dict[str, object]:
    summary: dict[str, object] = {
        "mix_name": mix_name,
        "LowStrategy": rows.loc[rows["regime"] == "Low", "strategy"].iloc[0],
        "MidStrategy": rows.loc[rows["regime"] == "Mid", "strategy"].iloc[0],
        "HighStrategy": rows.loc[rows["regime"] == "High", "strategy"].iloc[0],
        "LowDays": int(pd.to_numeric(rows.loc[rows["regime"] == "Low", "n_obs"]).iloc[0]),
        "MidDays": int(pd.to_numeric(rows.loc[rows["regime"] == "Mid", "n_obs"]).iloc[0]),
        "HighDays": int(pd.to_numeric(rows.loc[rows["regime"] == "High", "n_obs"]).iloc[0]),
    }
    summary["TotalDays"] = summary["LowDays"] + summary["MidDays"] + summary["HighDays"]

    for metric in WEIGHTED_METRIC_COLUMNS:
        summary[f"Weighted{metric}"] = weighted_mean(rows[metric], rows["n_obs"])
    return summary


def load_strategy_returns(results_dir: Path, strategy_name: str) -> pd.Series:
    path = results_dir / f"{strategy_name}.parquet"
    if not path.exists():
        raise FileNotFoundError(f"Missing result parquet for strategy '{strategy_name}': {path}")

    df = pd.read_parquet(path)
    idx = pd.to_datetime(df.index)
    if getattr(idx, "tz", None) is not None:
        idx = idx.tz_convert(None)
    df = df.copy()
    df.index = idx

    returns = strategy_return_series(df)
    returns.index = pd.to_datetime(returns.index)
    if getattr(returns.index, "tz", None) is not None:
        returns.index = returns.index.tz_convert(None)
    return returns.sort_index()


def stitch_mix_returns(
    regime_map: dict[str, str],
    results_dir: Path,
    min_coverage_ratio: float,
) -> tuple[pd.Series, pd.DataFrame]:
    strategy_returns = {
        strategy_name: load_strategy_returns(results_dir, strategy_name)
        for strategy_name in sorted(set(regime_map.values()))
    }

    combined_index = pd.DatetimeIndex(sorted(set().union(*[series.index for series in strategy_returns.values()])))
    benchmark = build_realized_vol_benchmark_regime(
        index=combined_index,
        min_coverage_ratio=min_coverage_ratio,
    )

    panel = benchmark.loc[:, ["benchmark_regime"]].copy()
    for strategy_name, returns in strategy_returns.items():
        panel[strategy_name] = returns.reindex(panel.index)

    chosen_returns = pd.Series(index=panel.index, dtype=float, name="stitched_return")
    chosen_strategy = pd.Series(index=panel.index, dtype=object, name="selected_strategy")
    for regime in REGIME_ORDER:
        mask = panel["benchmark_regime"].eq(regime)
        strategy_name = regime_map[regime]
        chosen_returns.loc[mask] = panel.loc[mask, strategy_name]
        chosen_strategy.loc[mask] = strategy_name

    panel["selected_strategy"] = chosen_strategy
    panel["stitched_return"] = chosen_returns
    panel = panel.dropna(subset=["benchmark_regime", "stitched_return"]).copy()
    return panel["stitched_return"], panel


def summarize_path_metrics(
    mix_name: str,
    regime_map: dict[str, str],
    results_dir: Path,
    ann_factor: float,
    min_coverage_ratio: float,
) -> dict[str, object]:
    stitched_returns, panel = stitch_mix_returns(
        regime_map=regime_map,
        results_dir=results_dir,
        min_coverage_ratio=min_coverage_ratio,
    )

    summary: dict[str, object] = {
        "mix_name": mix_name,
        "PathSharpe": sharpe_ratio_from_returns(stitched_returns, ann_factor=ann_factor),
        "PathAnnualizedVol": annualized_vol_from_returns(stitched_returns, ann_factor=ann_factor),
        "PathAnnualizedReturn": annualized_return_from_returns(
            stitched_returns, ann_factor=ann_factor
        ),
        "PathMaxDrawdown": max_drawdown_from_returns(stitched_returns),
        "PathCVaR": cvar_from_returns(stitched_returns),
        "PathDays": int(len(stitched_returns)),
    }
    for regime in REGIME_ORDER:
        summary[f"Path{regime}Days"] = int(panel["benchmark_regime"].eq(regime).sum())
    return summary


def build_path_export(panel: pd.DataFrame, mix_name: str) -> pd.DataFrame:
    out = panel.loc[:, ["benchmark_regime", "selected_strategy", "stitched_return"]].copy()
    out = out.rename(columns={"benchmark_regime": "regime", "stitched_return": "daily_return"})
    out.insert(0, "date", pd.to_datetime(out.index).normalize())
    out.insert(1, "mix_name", mix_name)
    return out.reset_index(drop=True)


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    path_output_path = Path(args.path_output)
    results_dir = Path(args.results_dir)

    df = load_input(input_path)

    summaries = []
    path_frames: list[pd.DataFrame] = []
    for mix_name, regime_map in PRESET_MIXES.items():
        weighted_summary = summarize_weighted_mix(
            mix_name, rows_for_mix(df, mix_name, regime_map)
        )
        stitched_returns, panel = stitch_mix_returns(
            regime_map=regime_map,
            results_dir=results_dir,
            min_coverage_ratio=args.min_coverage_ratio,
        )
        path_summary = {
            "mix_name": mix_name,
            "PathSharpe": sharpe_ratio_from_returns(stitched_returns, ann_factor=args.ann_factor),
            "PathAnnualizedVol": annualized_vol_from_returns(
                stitched_returns, ann_factor=args.ann_factor
            ),
            "PathAnnualizedReturn": annualized_return_from_returns(
                stitched_returns, ann_factor=args.ann_factor
            ),
            "PathMaxDrawdown": max_drawdown_from_returns(stitched_returns),
            "PathCVaR": cvar_from_returns(stitched_returns),
            "PathDays": int(len(stitched_returns)),
        }
        for regime in REGIME_ORDER:
            path_summary[f"Path{regime}Days"] = int(panel["benchmark_regime"].eq(regime).sum())
        summaries.append({**weighted_summary, **path_summary})
        path_frames.append(build_path_export(panel, mix_name))

    out = pd.DataFrame(summaries)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False)
    if path_frames:
        pd.concat(path_frames, ignore_index=True).to_csv(path_output_path, index=False)

    display_columns = [
        "mix_name",
        "WeightedSharpe",
        "PathSharpe",
        "WeightedAnnualizedVol",
        "PathAnnualizedVol",
        "WeightedAnnualizedReturn",
        "PathAnnualizedReturn",
        "WeightedMaxDrawdown",
        "PathMaxDrawdown",
        "WeightedCVaR",
        "PathCVaR",
        "LowDays",
        "MidDays",
        "HighDays",
        "TotalDays",
        "PathLowDays",
        "PathMidDays",
        "PathHighDays",
        "PathDays",
    ]
    print(out[display_columns].to_string(index=False))
    print(f"\nSaved regime-mix metrics to {output_path}")
    print(f"Saved stitched daily paths to {path_output_path}")


if __name__ == "__main__":
    main()
